#ifdef SDL_WINDOWPOS_ISCENTERED
	static constexpr auto WINDOWPOS_ISCENTERED(auto X)
	{
		return SDL_WINDOWPOS_ISCENTERED(X);
		#undef SDL_WINDOWPOS_ISCENTERED
	}
#endif

#ifdef SDL_WINDOWPOS_CENTERED
	static constexpr auto WINDOWPOS_CENTERED = SDL_WINDOWPOS_CENTERED;
	#undef SDL_WINDOWPOS_CENTERED
#endif

#ifdef SDL_WINDOWPOS_CENTERED_DISPLAY
	static constexpr auto WINDOWPOS_CENTERED_DISPLAY(auto X)
	{
		return SDL_WINDOWPOS_CENTERED_DISPLAY(X);
		#undef SDL_WINDOWPOS_CENTERED_DISPLAY
	}
#endif

#ifdef SDL_WINDOWPOS_CENTERED_MASK
	static constexpr auto WINDOWPOS_CENTERED_MASK = SDL_WINDOWPOS_CENTERED_MASK;
	#undef SDL_WINDOWPOS_CENTERED_MASK
#endif



#ifdef SDL_WINDOWPOS_ISUNDEFINED
	static constexpr auto WINDOWPOS_ISUNDEFINED(auto X)
	{
		return SDL_WINDOWPOS_ISUNDEFINED(X);
		#undef SDL_WINDOWPOS_ISUNDEFINED
	}
#endif

#ifdef SDL_WINDOWPOS_UNDEFINED
	static constexpr auto WINDOWPOS_UNDEFINED = SDL_WINDOWPOS_UNDEFINED;
	#undef SDL_WINDOWPOS_UNDEFINED
#endif

#ifdef SDL_WINDOWPOS_UNDEFINED_DISPLAY
	static constexpr auto WINDOWPOS_UNDEFINED_DISPLAY(auto X)
	{
		return SDL_WINDOWPOS_UNDEFINED_DISPLAY(X);
		#undef SDL_WINDOWPOS_UNDEFINED_DISPLAY
	}
#endif

#ifdef SDL_WINDOWPOS_UNDEFINED_MASK
	static constexpr auto WINDOWPOS_UNDEFINED_MASK = SDL_WINDOWPOS_UNDEFINED_MASK;
	#undef SDL_WINDOWPOS_UNDEFINED_MASK
#endif
