#ifdef SDL_HAPTIC_CONSTANT
	static constexpr auto HAPTIC_CONSTANT = SDL_HAPTIC_CONSTANT;
	#undef SDL_HAPTIC_CONSTANT
#endif

#ifdef SDL_HAPTIC_SINE
	static constexpr auto HAPTIC_SINE = SDL_HAPTIC_SINE;
	#undef SDL_HAPTIC_SINE
#endif

#ifdef SDL_HAPTIC_LEFTRIGHT
	static constexpr auto HAPTIC_LEFTRIGHT = SDL_HAPTIC_LEFTRIGHT;
	#undef SDL_HAPTIC_LEFTRIGHT
#endif

#ifdef SDL_HAPTIC_TRIANGLE
	static constexpr auto HAPTIC_TRIANGLE = SDL_HAPTIC_TRIANGLE;
	#undef SDL_HAPTIC_TRIANGLE
#endif

#ifdef SDL_HAPTIC_SAWTOOTHUP
	static constexpr auto HAPTIC_SAWTOOTHUP = SDL_HAPTIC_SAWTOOTHUP;
	#undef SDL_HAPTIC_SAWTOOTHUP
#endif

#ifdef SDL_HAPTIC_SAWTOOTHDOWN
	static constexpr auto HAPTIC_SAWTOOTHDOWN = SDL_HAPTIC_SAWTOOTHDOWN;
	#undef SDL_HAPTIC_SAWTOOTHDOWN
#endif

#ifdef SDL_HAPTIC_RAMP
	static constexpr auto HAPTIC_RAMP = SDL_HAPTIC_RAMP;
	#undef SDL_HAPTIC_RAMP
#endif

#ifdef SDL_HAPTIC_SPRING
	static constexpr auto HAPTIC_SPRING = SDL_HAPTIC_SPRING;
	#undef SDL_HAPTIC_SPRING
#endif

#ifdef SDL_HAPTIC_DAMPER
	static constexpr auto HAPTIC_DAMPER = SDL_HAPTIC_DAMPER;
	#undef SDL_HAPTIC_DAMPER
#endif

#ifdef SDL_HAPTIC_INERTIA
	static constexpr auto HAPTIC_INERTIA = SDL_HAPTIC_INERTIA;
	#undef SDL_HAPTIC_INERTIA
#endif

#ifdef SDL_HAPTIC_FRICTION
	static constexpr auto HAPTIC_FRICTION = SDL_HAPTIC_FRICTION;
	#undef SDL_HAPTIC_FRICTION
#endif

#ifdef SDL_HAPTIC_CUSTOM
	static constexpr auto HAPTIC_CUSTOM = SDL_HAPTIC_CUSTOM;
	#undef SDL_HAPTIC_CUSTOM
#endif

#ifdef SDL_HAPTIC_GAIN
	static constexpr auto HAPTIC_GAIN = SDL_HAPTIC_GAIN;
	#undef SDL_HAPTIC_GAIN
#endif

#ifdef SDL_HAPTIC_AUTOCENTER
	static constexpr auto HAPTIC_AUTOCENTER = SDL_HAPTIC_AUTOCENTER;
	#undef SDL_HAPTIC_AUTOCENTER
#endif

#ifdef SDL_HAPTIC_STATUS
	static constexpr auto HAPTIC_STATUS = SDL_HAPTIC_STATUS;
#endif

#ifdef SDL_HAPTIC_PAUSE
	static constexpr auto HAPTIC_PAUSE = SDL_HAPTIC_PAUSE;
	#undef SDL_HAPTIC_PAUSE
#endif

#ifdef SDL_HAPTIC_POLAR
	static constexpr auto HAPTIC_POLAR = SDL_HAPTIC_POLAR;
	#undef SDL_HAPTIC_POLAR
#endif

#ifdef SDL_HAPTIC_CARTESIAN
	static constexpr auto HAPTIC_CARTESIAN = SDL_HAPTIC_CARTESIAN;
	#undef SDL_HAPTIC_CARTESIAN
#endif

#ifdef SDL_HAPTIC_SPHERICAL
	static constexpr auto HAPTIC_SPHERICAL = SDL_HAPTIC_SPHERICAL;
	#undef SDL_HAPTIC_SPHERICAL
#endif

#ifdef SDL_HAPTIC_STEERING_AXIS
	static constexpr auto HAPTIC_STEERING_AXIS = SDL_HAPTIC_STEERING_AXIS;
	#undef SDL_HAPTIC_STEERING_AXIS
#endif

#ifdef SDL_HAPTIC_INFINITY
	static constexpr auto HAPTIC_INFINITY = SDL_HAPTIC_INFINITY;
	#undef SDL_HAPTIC_INFINITY
#endif
