#ifdef SDL_HINT_FRAMEBUFFER_ACCELERATION
	static constexpr auto HINT_FRAMEBUFFER_ACCELERATION = SDL_HINT_FRAMEBUFFER_ACCELERATION;
	#undef SDL_HINT_FRAMEBUFFER_ACCELERATION
#endif

#ifdef SDL_HINT_RENDER_DRIVER
	static constexpr auto HINT_RENDER_DRIVER = SDL_HINT_RENDER_DRIVER;
	#undef SDL_HINT_RENDER_DRIVER
#endif

#ifdef SDL_HINT_RENDER_OPENGL_SHADERS
	static constexpr auto HINT_RENDER_OPENGL_SHADERS = SDL_HINT_RENDER_OPENGL_SHADERS;
	#undef SDL_HINT_RENDER_OPENGL_SHADERS
#endif

#ifdef SDL_HINT_RENDER_DIRECT3D_THREADSAFE
	static constexpr auto HINT_RENDER_DIRECT3D_THREADSAFE = SDL_HINT_RENDER_DIRECT3D_THREADSAFE;
	#undef SDL_HINT_RENDER_DIRECT3D_THREADSAFE
#endif

#ifdef SDL_HINT_RENDER_DIRECT3D11_DEBUG
	static constexpr auto HINT_RENDER_DIRECT3D11_DEBUG = SDL_HINT_RENDER_DIRECT3D11_DEBUG;
	#undef SDL_HINT_RENDER_DIRECT3D11_DEBUG
#endif

#ifdef SDL_HINT_RENDER_LOGICAL_SIZE_MODE
	static constexpr auto HINT_RENDER_LOGICAL_SIZE_MODE = SDL_HINT_RENDER_LOGICAL_SIZE_MODE;
	#undef SDL_HINT_RENDER_LOGICAL_SIZE_MODE
#endif

#ifdef SDL_HINT_RENDER_SCALE_QUALITY
	static constexpr auto HINT_RENDER_SCALE_QUALITY = SDL_HINT_RENDER_SCALE_QUALITY;
	#undef SDL_HINT_RENDER_SCALE_QUALITY
#endif

#ifdef SDL_HINT_RENDER_VSYNC
	static constexpr auto HINT_RENDER_VSYNC = SDL_HINT_RENDER_VSYNC;
	#undef SDL_HINT_RENDER_VSYNC
#endif

#ifdef SDL_HINT_VIDEO_ALLOW_SCREENSAVER
	static constexpr auto HINT_VIDEO_ALLOW_SCREENSAVER = SDL_HINT_VIDEO_ALLOW_SCREENSAVER;
	#undef SDL_HINT_VIDEO_ALLOW_SCREENSAVER
#endif

#ifdef SDL_HINT_VIDEO_EXTERNAL_CONTEXT
	static constexpr auto HINT_VIDEO_EXTERNAL_CONTEXT = SDL_HINT_VIDEO_EXTERNAL_CONTEXT;
	#undef SDL_HINT_VIDEO_EXTERNAL_CONTEXT
#endif

#ifdef SDL_HINT_VIDEO_X11_XVIDMODE
	static constexpr auto HINT_VIDEO_X11_XVIDMODE = SDL_HINT_VIDEO_X11_XVIDMODE;
	#undef SDL_HINT_VIDEO_X11_XVIDMODE
#endif

#ifdef SDL_HINT_VIDEO_X11_XINERAMA
	static constexpr auto HINT_VIDEO_X11_XINERAMA = SDL_HINT_VIDEO_X11_XINERAMA;
	#undef SDL_HINT_VIDEO_X11_XINERAMA
#endif

#ifdef SDL_HINT_VIDEO_X11_XRANDR
	static constexpr auto HINT_VIDEO_X11_XRANDR = SDL_HINT_VIDEO_X11_XRANDR;
	#undef SDL_HINT_VIDEO_X11_XRANDR
#endif

#ifdef SDL_HINT_VIDEO_X11_WINDOW_VISUALID
	static constexpr auto HINT_VIDEO_X11_WINDOW_VISUALID = SDL_HINT_VIDEO_X11_WINDOW_VISUALID;
	#undef SDL_HINT_VIDEO_X11_WINDOW_VISUALID
#endif

#ifdef SDL_HINT_VIDEO_X11_NET_WM_PING
	static constexpr auto HINT_VIDEO_X11_NET_WM_PING = SDL_HINT_VIDEO_X11_NET_WM_PING;
	#undef SDL_HINT_VIDEO_X11_NET_WM_PING
#endif

#ifdef SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR
	static constexpr auto HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR = SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR;
	#undef SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR
#endif

#ifdef SDL_HINT_VIDEO_X11_FORCE_EGL
	static constexpr auto HINT_VIDEO_X11_FORCE_EGL = SDL_HINT_VIDEO_X11_FORCE_EGL;
	#undef SDL_HINT_VIDEO_X11_FORCE_EGL
#endif

#ifdef SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN
	static constexpr auto HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN = SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN;
	#undef SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN
#endif

#ifdef SDL_HINT_WINDOWS_INTRESOURCE_ICON
	static constexpr auto HINT_WINDOWS_INTRESOURCE_ICON = SDL_HINT_WINDOWS_INTRESOURCE_ICON;
	#undef SDL_HINT_WINDOWS_INTRESOURCE_ICON
#endif

#ifdef SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL
	static constexpr auto HINT_WINDOWS_INTRESOURCE_ICON_SMALL = SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL;
	#undef SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL
#endif

#ifdef SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP
	static constexpr auto HINT_WINDOWS_ENABLE_MESSAGELOOP = SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP;
	#undef SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP
#endif

#ifdef SDL_HINT_GRAB_KEYBOARD
	static constexpr auto HINT_GRAB_KEYBOARD = SDL_HINT_GRAB_KEYBOARD;
	#undef SDL_HINT_GRAB_KEYBOARD
#endif

#ifdef SDL_HINT_MOUSE_DOUBLE_CLICK_TIME
	static constexpr auto HINT_MOUSE_DOUBLE_CLICK_TIME = SDL_HINT_MOUSE_DOUBLE_CLICK_TIME;
	#undef SDL_HINT_MOUSE_DOUBLE_CLICK_TIME
#endif

#ifdef SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS
	static constexpr auto HINT_MOUSE_DOUBLE_CLICK_RADIUS = SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS;
	#undef SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS
#endif

#ifdef SDL_HINT_MOUSE_NORMAL_SPEED_SCALE
	static constexpr auto HINT_MOUSE_NORMAL_SPEED_SCALE = SDL_HINT_MOUSE_NORMAL_SPEED_SCALE;
	#undef SDL_HINT_MOUSE_NORMAL_SPEED_SCALE
#endif

#ifdef SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE
	static constexpr auto HINT_MOUSE_RELATIVE_SPEED_SCALE = SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE;
	#undef SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE
#endif

#ifdef SDL_HINT_MOUSE_RELATIVE_SCALING
	static constexpr auto HINT_MOUSE_RELATIVE_SCALING = SDL_HINT_MOUSE_RELATIVE_SCALING;
	#undef SDL_HINT_MOUSE_RELATIVE_SCALING
#endif

#ifdef SDL_HINT_MOUSE_RELATIVE_MODE_WARP
	static constexpr auto HINT_MOUSE_RELATIVE_MODE_WARP = SDL_HINT_MOUSE_RELATIVE_MODE_WARP;
	#undef SDL_HINT_MOUSE_RELATIVE_MODE_WARP
#endif

#ifdef SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH
	static constexpr auto HINT_MOUSE_FOCUS_CLICKTHROUGH = SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH;
	#undef SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH
#endif

#ifdef SDL_HINT_TOUCH_MOUSE_EVENTS
	static constexpr auto HINT_TOUCH_MOUSE_EVENTS = SDL_HINT_TOUCH_MOUSE_EVENTS;
	#undef SDL_HINT_TOUCH_MOUSE_EVENTS
#endif

#ifdef SDL_HINT_MOUSE_TOUCH_EVENTS
	static constexpr auto HINT_MOUSE_TOUCH_EVENTS = SDL_HINT_MOUSE_TOUCH_EVENTS;
	#undef SDL_HINT_MOUSE_TOUCH_EVENTS
#endif

#ifdef SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS
	static constexpr auto HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS = SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS;
	#undef SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS
#endif

#ifdef SDL_HINT_IDLE_TIMER_DISABLED
	static constexpr auto HINT_IDLE_TIMER_DISABLED = SDL_HINT_IDLE_TIMER_DISABLED;
	#undef SDL_HINT_IDLE_TIMER_DISABLED
#endif

#ifdef SDL_HINT_ORIENTATIONS
	static constexpr auto HINT_ORIENTATIONS = SDL_HINT_ORIENTATIONS;
	#undef SDL_HINT_ORIENTATIONS
#endif

#ifdef SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS
	static constexpr auto HINT_APPLE_TV_CONTROLLER_UI_EVENTS = SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS;
	#undef SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS
#endif

#ifdef SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION
	static constexpr auto HINT_APPLE_TV_REMOTE_ALLOW_ROTATION = SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION;
	#undef SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION
#endif

#ifdef SDL_HINT_IOS_HIDE_HOME_INDICATOR
	static constexpr auto HINT_IOS_HIDE_HOME_INDICATOR = SDL_HINT_IOS_HIDE_HOME_INDICATOR;
	#undef SDL_HINT_IOS_HIDE_HOME_INDICATOR
#endif

#ifdef SDL_HINT_ACCELEROMETER_AS_JOYSTICK
	static constexpr auto HINT_ACCELEROMETER_AS_JOYSTICK = SDL_HINT_ACCELEROMETER_AS_JOYSTICK;
	#undef SDL_HINT_ACCELEROMETER_AS_JOYSTICK
#endif

#ifdef SDL_HINT_TV_REMOTE_AS_JOYSTICK
	static constexpr auto HINT_TV_REMOTE_AS_JOYSTICK = SDL_HINT_TV_REMOTE_AS_JOYSTICK;
	#undef SDL_HINT_TV_REMOTE_AS_JOYSTICK
#endif

#ifdef SDL_HINT_XINPUT_ENABLED
	static constexpr auto HINT_XINPUT_ENABLED = SDL_HINT_XINPUT_ENABLED;
	#undef SDL_HINT_XINPUT_ENABLED
#endif

#ifdef SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING
	static constexpr auto HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING = SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING;
	#undef SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING
#endif

#ifdef SDL_HINT_GAMECONTROLLERTYPE
	static constexpr auto HINT_GAMECONTROLLERTYPE = SDL_HINT_GAMECONTROLLERTYPE;
	#undef SDL_HINT_GAMECONTROLLERTYPE
#endif

#ifdef SDL_HINT_GAMECONTROLLERCONFIG
	static constexpr auto HINT_GAMECONTROLLERCONFIG = SDL_HINT_GAMECONTROLLERCONFIG;
	#undef SDL_HINT_GAMECONTROLLERCONFIG
#endif

#ifdef SDL_HINT_GAMECONTROLLERCONFIG_FILE
	static constexpr auto HINT_GAMECONTROLLERCONFIG_FILE = SDL_HINT_GAMECONTROLLERCONFIG_FILE;
	#undef SDL_HINT_GAMECONTROLLERCONFIG_FILE
#endif

#ifdef SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES
	static constexpr auto HINT_GAMECONTROLLER_IGNORE_DEVICES = SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES;
	#undef SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES
#endif

#ifdef SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT
	static constexpr auto HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT = SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT;
	#undef SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT
#endif

#ifdef SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS
	static constexpr auto HINT_GAMECONTROLLER_USE_BUTTON_LABELS = SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS;
	#undef SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS
#endif

#ifdef SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS
	static constexpr auto HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS = SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS;
	#undef SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS
#endif

#ifdef SDL_HINT_JOYSTICK_HIDAPI
	static constexpr auto HINT_JOYSTICK_HIDAPI = SDL_HINT_JOYSTICK_HIDAPI;
	#undef SDL_HINT_JOYSTICK_HIDAPI
#endif

#ifdef SDL_HINT_JOYSTICK_HIDAPI_PS4
	static constexpr auto HINT_JOYSTICK_HIDAPI_PS4 = SDL_HINT_JOYSTICK_HIDAPI_PS4;
	#undef SDL_HINT_JOYSTICK_HIDAPI_PS4
#endif

#ifdef SDL_HINT_JOYSTICK_HIDAPI_PS5
	static constexpr auto HINT_JOYSTICK_HIDAPI_PS5 = SDL_HINT_JOYSTICK_HIDAPI_PS5;
	#undef SDL_HINT_JOYSTICK_HIDAPI_PS5
#endif

#ifdef SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE
	static constexpr auto HINT_JOYSTICK_HIDAPI_PS4_RUMBLE = SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE;
	#undef SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE
#endif

#ifdef SDL_HINT_JOYSTICK_HIDAPI_STEAM
	static constexpr auto HINT_JOYSTICK_HIDAPI_STEAM = SDL_HINT_JOYSTICK_HIDAPI_STEAM;
	#undef SDL_HINT_JOYSTICK_HIDAPI_STEAM
#endif

#ifdef SDL_HINT_JOYSTICK_HIDAPI_SWITCH
	static constexpr auto HINT_JOYSTICK_HIDAPI_SWITCH = SDL_HINT_JOYSTICK_HIDAPI_SWITCH;
	#undef SDL_HINT_JOYSTICK_HIDAPI_SWITCH
#endif

#ifdef SDL_HINT_JOYSTICK_HIDAPI_XBOX
	static constexpr auto HINT_JOYSTICK_HIDAPI_XBOX = SDL_HINT_JOYSTICK_HIDAPI_XBOX;
	#undef SDL_HINT_JOYSTICK_HIDAPI_XBOX
#endif

#ifdef SDL_HINT_JOYSTICK_HIDAPI_CORRELATE_XINPUT
	static constexpr auto HINT_JOYSTICK_HIDAPI_CORRELATE_XINPUT = SDL_HINT_JOYSTICK_HIDAPI_CORRELATE_XINPUT;
	#undef SDL_HINT_JOYSTICK_HIDAPI_CORRELATE_XINPUT
#endif

#ifdef SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE
	static constexpr auto HINT_JOYSTICK_HIDAPI_GAMECUBE = SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE;
	#undef SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE
#endif

#ifdef SDL_HINT_ENABLE_STEAM_CONTROLLERS
	static constexpr auto HINT_ENABLE_STEAM_CONTROLLERS = SDL_HINT_ENABLE_STEAM_CONTROLLERS;
	#undef SDL_HINT_ENABLE_STEAM_CONTROLLERS
#endif

#ifdef SDL_HINT_JOYSTICK_RAWINPUT
	static constexpr auto HINT_JOYSTICK_RAWINPUT = SDL_HINT_JOYSTICK_RAWINPUT;
	#undef SDL_HINT_JOYSTICK_RAWINPUT
#endif

#ifdef SDL_HINT_JOYSTICK_THREAD
	static constexpr auto HINT_JOYSTICK_THREAD = SDL_HINT_JOYSTICK_THREAD;
	#undef SDL_HINT_JOYSTICK_THREAD
#endif

#ifdef SDL_HINT_LINUX_JOYSTICK_DEADZONES
	static constexpr auto HINT_LINUX_JOYSTICK_DEADZONES = SDL_HINT_LINUX_JOYSTICK_DEADZONES;
	#undef SDL_HINT_LINUX_JOYSTICK_DEADZONES
#endif

#ifdef SDL_HINT_ALLOW_TOPMOST
	static constexpr auto HINT_ALLOW_TOPMOST = SDL_HINT_ALLOW_TOPMOST;
	#undef SDL_HINT_ALLOW_TOPMOST
#endif

#ifdef SDL_HINT_TIMER_RESOLUTION
	static constexpr auto HINT_TIMER_RESOLUTION = SDL_HINT_TIMER_RESOLUTION;
	#undef SDL_HINT_TIMER_RESOLUTION
#endif

#ifdef SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION
	static constexpr auto HINT_QTWAYLAND_CONTENT_ORIENTATION = SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION;
	#undef SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION
#endif

#ifdef SDL_HINT_QTWAYLAND_WINDOW_FLAGS
	static constexpr auto HINT_QTWAYLAND_WINDOW_FLAGS = SDL_HINT_QTWAYLAND_WINDOW_FLAGS;
	#undef SDL_HINT_QTWAYLAND_WINDOW_FLAGS
#endif

#ifdef SDL_HINT_THREAD_STACK_SIZE
	static constexpr auto HINT_THREAD_STACK_SIZE = SDL_HINT_THREAD_STACK_SIZE;
	#undef SDL_HINT_THREAD_STACK_SIZE
#endif

#ifdef SDL_HINT_THREAD_PRIORITY_POLICY
	static constexpr auto HINT_THREAD_PRIORITY_POLICY = SDL_HINT_THREAD_PRIORITY_POLICY;
	#undef SDL_HINT_THREAD_PRIORITY_POLICY
#endif

#ifdef SDL_HINT_THREAD_FORCE_REALTIME_TIME_CRITICAL
	static constexpr auto HINT_THREAD_FORCE_REALTIME_TIME_CRITICAL = SDL_HINT_THREAD_FORCE_REALTIME_TIME_CRITICAL;
	#undef SDL_HINT_THREAD_FORCE_REALTIME_TIME_CRITICAL
#endif

#ifdef SDL_HINT_VIDEO_HIGHDPI_DISABLED
	static constexpr auto HINT_VIDEO_HIGHDPI_DISABLED = SDL_HINT_VIDEO_HIGHDPI_DISABLED;
	#undef SDL_HINT_VIDEO_HIGHDPI_DISABLED
#endif

#ifdef SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK
	static constexpr auto HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK = SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK;
	#undef SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK
#endif

#ifdef SDL_HINT_VIDEO_WIN_D3DCOMPILER
	static constexpr auto HINT_VIDEO_WIN_D3DCOMPILER = SDL_HINT_VIDEO_WIN_D3DCOMPILER;
	#undef SDL_HINT_VIDEO_WIN_D3DCOMPILER
#endif

#ifdef SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT
	static constexpr auto HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT = SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT;
	#undef SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT
#endif

#ifdef SDL_HINT_WINRT_PRIVACY_POLICY_URL
	static constexpr auto HINT_WINRT_PRIVACY_POLICY_URL = SDL_HINT_WINRT_PRIVACY_POLICY_URL;
	#undef SDL_HINT_WINRT_PRIVACY_POLICY_URL
#endif

#ifdef SDL_HINT_WINRT_PRIVACY_POLICY_LABEL
	static constexpr auto HINT_WINRT_PRIVACY_POLICY_LABEL = SDL_HINT_WINRT_PRIVACY_POLICY_LABEL;
	#undef SDL_HINT_WINRT_PRIVACY_POLICY_LABEL
#endif

#ifdef SDL_HINT_WINRT_HANDLE_BACK_BUTTON
	static constexpr auto HINT_WINRT_HANDLE_BACK_BUTTON = SDL_HINT_WINRT_HANDLE_BACK_BUTTON;
	#undef SDL_HINT_WINRT_HANDLE_BACK_BUTTON
#endif

#ifdef SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES
	static constexpr auto HINT_VIDEO_MAC_FULLSCREEN_SPACES = SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES;
	#undef SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES
#endif

#ifdef SDL_HINT_MAC_BACKGROUND_APP
	static constexpr auto HINT_MAC_BACKGROUND_APP = SDL_HINT_MAC_BACKGROUND_APP;
	#undef SDL_HINT_MAC_BACKGROUND_APP
#endif

#ifdef SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION
	static constexpr auto HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION = SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION;
	#undef SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION
#endif

#ifdef SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION
	static constexpr auto HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION = SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION;
	#undef SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION
#endif

#ifdef SDL_HINT_IME_INTERNAL_EDITING
	static constexpr auto HINT_IME_INTERNAL_EDITING = SDL_HINT_IME_INTERNAL_EDITING;
	#undef SDL_HINT_IME_INTERNAL_EDITING
#endif

#ifdef SDL_HINT_ANDROID_TRAP_BACK_BUTTON
	static constexpr auto HINT_ANDROID_TRAP_BACK_BUTTON = SDL_HINT_ANDROID_TRAP_BACK_BUTTON;
	#undef SDL_HINT_ANDROID_TRAP_BACK_BUTTON
#endif

#ifdef SDL_HINT_ANDROID_BLOCK_ON_PAUSE
	static constexpr auto HINT_ANDROID_BLOCK_ON_PAUSE = SDL_HINT_ANDROID_BLOCK_ON_PAUSE;
	#undef SDL_HINT_ANDROID_BLOCK_ON_PAUSE
#endif

#ifdef SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO
	static constexpr auto HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO = SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO;
	#undef SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO
#endif

#ifdef SDL_HINT_RETURN_KEY_HIDES_IME
	static constexpr auto HINT_RETURN_KEY_HIDES_IME = SDL_HINT_RETURN_KEY_HIDES_IME;
	#undef SDL_HINT_RETURN_KEY_HIDES_IME
#endif

#ifdef SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT
	static constexpr auto HINT_EMSCRIPTEN_KEYBOARD_ELEMENT = SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT;
	#undef SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT
#endif

#ifdef SDL_HINT_EMSCRIPTEN_ASYNCIFY
	static constexpr auto HINT_EMSCRIPTEN_ASYNCIFY = SDL_HINT_EMSCRIPTEN_ASYNCIFY;
	#undef SDL_HINT_EMSCRIPTEN_ASYNCIFY
#endif

#ifdef SDL_HINT_NO_SIGNAL_HANDLERS
	static constexpr auto HINT_NO_SIGNAL_HANDLERS = SDL_HINT_NO_SIGNAL_HANDLERS;
	#undef SDL_HINT_NO_SIGNAL_HANDLERS
#endif

#ifdef SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4
	static constexpr auto HINT_WINDOWS_NO_CLOSE_ON_ALT_F4 = SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4;
	#undef SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4
#endif

#ifdef SDL_HINT_BMP_SAVE_LEGACY_FORMAT
	static constexpr auto HINT_BMP_SAVE_LEGACY_FORMAT = SDL_HINT_BMP_SAVE_LEGACY_FORMAT;
	#undef SDL_HINT_BMP_SAVE_LEGACY_FORMAT
#endif

#ifdef SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING
	static constexpr auto HINT_WINDOWS_DISABLE_THREAD_NAMING = SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING;
	#undef SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING
#endif

#ifdef SDL_HINT_RPI_VIDEO_LAYER
	static constexpr auto HINT_RPI_VIDEO_LAYER = SDL_HINT_RPI_VIDEO_LAYER;
	#undef SDL_HINT_RPI_VIDEO_LAYER
#endif

#ifdef SDL_HINT_VIDEO_DOUBLE_BUFFER
	static constexpr auto HINT_VIDEO_DOUBLE_BUFFER = SDL_HINT_VIDEO_DOUBLE_BUFFER;
	#undef SDL_HINT_VIDEO_DOUBLE_BUFFER
#endif

#ifdef SDL_HINT_OPENGL_ES_DRIVER
	static constexpr auto HINT_OPENGL_ES_DRIVER = SDL_HINT_OPENGL_ES_DRIVER;
	#undef SDL_HINT_OPENGL_ES_DRIVER
#endif

#ifdef SDL_HINT_AUDIO_RESAMPLING_MODE
	static constexpr auto HINT_AUDIO_RESAMPLING_MODE = SDL_HINT_AUDIO_RESAMPLING_MODE;
	#undef SDL_HINT_AUDIO_RESAMPLING_MODE
#endif

#ifdef SDL_HINT_AUDIO_CATEGORY
	static constexpr auto HINT_AUDIO_CATEGORY = SDL_HINT_AUDIO_CATEGORY;
	#undef SDL_HINT_AUDIO_CATEGORY
#endif

#ifdef SDL_HINT_RENDER_BATCHING
	static constexpr auto HINT_RENDER_BATCHING = SDL_HINT_RENDER_BATCHING;
	#undef SDL_HINT_RENDER_BATCHING
#endif

#ifdef SDL_HINT_AUTO_UPDATE_JOYSTICKS
	static constexpr auto HINT_AUTO_UPDATE_JOYSTICKS = SDL_HINT_AUTO_UPDATE_JOYSTICKS;
	#undef SDL_HINT_AUTO_UPDATE_JOYSTICKS
#endif

#ifdef SDL_HINT_AUTO_UPDATE_SENSORS
	static constexpr auto HINT_AUTO_UPDATE_SENSORS = SDL_HINT_AUTO_UPDATE_SENSORS;
	#undef SDL_HINT_AUTO_UPDATE_SENSORS
#endif

#ifdef SDL_HINT_EVENT_LOGGING
	static constexpr auto HINT_EVENT_LOGGING = SDL_HINT_EVENT_LOGGING;
	#undef SDL_HINT_EVENT_LOGGING
#endif

#ifdef SDL_HINT_WAVE_RIFF_CHUNK_SIZE
	static constexpr auto HINT_WAVE_RIFF_CHUNK_SIZE = SDL_HINT_WAVE_RIFF_CHUNK_SIZE;
	#undef SDL_HINT_WAVE_RIFF_CHUNK_SIZE
#endif

#ifdef SDL_HINT_WAVE_TRUNCATION
	static constexpr auto HINT_WAVE_TRUNCATION = SDL_HINT_WAVE_TRUNCATION;
	#undef SDL_HINT_WAVE_TRUNCATION
#endif

#ifdef SDL_HINT_WAVE_FACT_CHUNK
	static constexpr auto HINT_WAVE_FACT_CHUNK = SDL_HINT_WAVE_FACT_CHUNK;
	#undef SDL_HINT_WAVE_FACT_CHUNK
#endif

#ifdef SDL_HINT_DISPLAY_USABLE_BOUNDS
	static constexpr auto HINT_DISPLAY_USABLE_BOUNDS = SDL_HINT_DISPLAY_USABLE_BOUNDS;
	#undef SDL_HINT_DISPLAY_USABLE_BOUNDS
#endif

#ifdef SDL_HINT_AUDIO_DEVICE_APP_NAME
	static constexpr auto HINT_AUDIO_DEVICE_APP_NAME = SDL_HINT_AUDIO_DEVICE_APP_NAME;
	#undef SDL_HINT_AUDIO_DEVICE_APP_NAME
#endif

#ifdef SDL_HINT_AUDIO_DEVICE_STREAM_NAME
	static constexpr auto HINT_AUDIO_DEVICE_STREAM_NAME = SDL_HINT_AUDIO_DEVICE_STREAM_NAME;
	#undef SDL_HINT_AUDIO_DEVICE_STREAM_NAME
#endif

#ifdef SDL_HINT_PREFERRED_LOCALES
	static constexpr auto HINT_PREFERRED_LOCALES = SDL_HINT_PREFERRED_LOCALES;
	#undef SDL_HINT_PREFERRED_LOCALES
#endif

